---
name: WarnSystem
main: machi\warn
version: 1.0.0
api:
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
- 4.0.3
author: MazaiCrafty
commands:
 /warn:
  usage: "//warn <player> <0,1,2,3>"
  desctiption: "execute warning"
...
